spring.application.name=service-registry
server.port=8761

#by default, each eureka server is also a eureka client and we are going to disable client-side behaviour by configuring these properties
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
