spring.application.name=api-gateway
server.port=9191
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

## Routes for Employee Service
spring.cloud.gateway.routes[0].id=
spring.cloud.gateway.routes[0].uri=