FROM eclipse-temurin:17

LABEL maintainer="asifuzzaman.opi@gmail.com"

WORKDIR /app

COPY target/department-0.0.1-SNAPSHOT.jar department-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","department-0.0.1-SNAPSHOT.jar"]